version: '3'
services:
  prometheus:
    container_name: 'prometheus_1'
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    container_name: 'grafana_1'
    image: grafana/grafana:8.0.5
    depends_on:
      - prometheus
    ports:
    - "3000:3000"
